// types
export const LOAD_INITIAL = 'LOAD_INITIAL';
export const UPDATE_WIDGET_CONFIG = "UPDATE_WIDGET_CONFIG";

export const UPDATE_DATASETS = 'UPDATE_DATASETS';
export const UPDATE_DATASETS_LOADING = 'UPDATE_DATASETS_LOADING';