# Generated by Django 4.2.8 on 2024-02-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodash', '0003_mapchartwidget'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapwidget',
            name='basemap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapwidget',
            name='has_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mapwidget',
            name='labels',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapwidget',
            name='show_boundaries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapwidget',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
