# Generated by Django 4.2.8 on 2024-02-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodash', '0005_mapwidget_bounds_mapwidget_lat_mapwidget_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapwidget',
            name='zoom',
            field=models.FloatField(blank=True, default=2.0, null=True),
        ),
    ]
