# Generated by Django 4.2.8 on 2024-02-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodash', '0006_alter_mapwidget_zoom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapwidget',
            name='bounds',
        ),
    ]
