# Generated by Django 4.2.8 on 2024-02-20 16:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('geodash', '0007_remove_mapwidget_bounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField()),
                ('body', wagtail.fields.StreamField([('text_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(form_classname='heading', required=True)), ('sub_heading', wagtail.blocks.CharBlock(form_classname='subheading', required=False)), ('text', wagtail.blocks.RichTextBlock(required=True))])), ('map_widget_block', wagtail.blocks.StructBlock([('map_widget', wagtail.snippets.blocks.SnippetChooserBlock('geodash.MapWidget', required=True)), ('full_width', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('map_widget_with_text_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(form_classname='heading', required=False)), ('text', wagtail.blocks.RichTextBlock(required=True)), ('map_widget', wagtail.snippets.blocks.SnippetChooserBlock('geodash.MapWidget', required=True))]))], blank=True, use_json_field=True, verbose_name='Page body')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
