# Generated by Django 4.2.8 on 2024-02-20 16:43

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('geodash', '0008_dashboardpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpage',
            name='body',
            field=wagtail.fields.StreamField([('text_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(form_classname='heading', required=True)), ('sub_heading', wagtail.blocks.CharBlock(form_classname='subheading', required=False)), ('text', wagtail.blocks.RichTextBlock(required=True))])), ('map_widget_block', wagtail.blocks.StructBlock([('map_widget', wagtail.snippets.blocks.SnippetChooserBlock('geodash.MapWidget', required=True)), ('full_width', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('map_widget_with_text_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(form_classname='heading', required=False)), ('text', wagtail.blocks.RichTextBlock(required=True)), ('map_widget', wagtail.snippets.blocks.SnippetChooserBlock('geodash.MapWidget', required=True)), ('map_position', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')]))]))], blank=True, use_json_field=True, verbose_name='Page body'),
        ),
    ]
